Repository dlang-community/dfmt, pull requests merged in 2018-02, with the labels that each got.

#333 Fix pkg file to put bash-completion into the right place
  bash-completion/completions/dfmt
  pkg/dfmt.pkg
Labels: Bug Fix, auto-merge

#336 Fix bad formatting in main.d
  src/dfmt/main.d
Labels: Bug Fix, auto-merge

#335 Change to more effcient optionsToString template
  src/dfmt/main.d
Labels: auto-merge

#334 Fix Imports to point to the actual symbols rather then wrongly imported ones
  src/dfmt/globmatch_editorconfig.d
  src/dfmt/main.d
Labels: auto-merge-rebase

#338 [trivial] Fix spacing in the README example
  README.md
Labels: auto-merge-squash, trivial
