Repository dlang-community/dfmt, pull requests merged in 2018-10, with the labels that each got.

#390 fix #244 - Wrong indentation for bool enums
  src/dfmt/formatter.d
  tests/allman/issue0244.d.ref
  tests/issue0244.d
  tests/otbs/issue0244.d.ref
Labels: Bug Fix, auto-merge-rebase

#392 Fix #246 - Questionable indentation for multiple `with` statements
  src/dfmt/formatter.d
  tests/allman/issue0246.d.ref
  tests/issue0246.d
  tests/otbs/issue0246.d.ref
Labels: auto-merge-rebase

#393 Fix #286 - Weird indentation in else branch after wrapping expression
  src/dfmt/formatter.d
  tests/allman/issue0286.d.ref
  tests/issue0286.d
  tests/otbs/issue0286.d.ref
Labels: auto-merge-squash

#394 Fix #326 - Spaces missing after attributes in function literals
  src/dfmt/formatter.d
  tests/allman/issue0326.d.ref
  tests/issue0326.d
  tests/otbs/issue0326.d.ref
Labels: auto-merge-squash

#396 Debug with param
  src/dfmt/formatter.d
  tests/allman/debug_with_param.d.ref
  tests/debug_with_param.d
  tests/otbs/debug_with_param.d.ref
Labels: Bug Fix, auto-merge

#398 Fix #345 - Case of trailing white space
  src/dfmt/formatter.d
  tests/allman/attribute_constraint.d.ref
  tests/allman/issue0153.d.ref
  tests/allman/issue0345.d.ref
  tests/issue0345.args
  tests/issue0345.d
  tests/otbs/attribute_constraint.d.ref
  tests/otbs/issue0153.d.ref
  tests/otbs/issue0345.d.ref
Labels: auto-merge

#399 Fix #349 - Wrong indentation of access modifier after break of long line
  src/dfmt/formatter.d
  tests/allman/issue0349.d.ref
  tests/issue0349.d
  tests/otbs/issue0349.d.ref
Labels: auto-merge-rebase

#400 Fix #287 - Extra space after import in delegate
  src/dfmt/formatter.d
  tests/allman/issue0287.d.ref
  tests/issue0287.d
  tests/otbs/issue0287.d.ref
Labels: auto-merge-rebase

#403 Allow comments in selective imports.
  src/dfmt/formatter.d
  tests/allman/issue0349.d.ref
  tests/allman/issue0384.d.ref
  tests/issue0349.d
  tests/issue0384.d
  tests/otbs/issue0349.d.ref
  tests/otbs/issue0384.d.ref
Labels: Bug Fix, auto-merge-squash
