Repository dlang-community/dfmt, pull requests merged in 2018-09, with the labels that each got.

#377 Deprecate enforce ex
  src/dfmt/main.d
Labels: auto-merge-squash

#368 Add index validity checks to the left paren/bracket code. Fixes #367.
  src/dfmt/formatter.d
Labels: Bug Fix, auto-merge-squash

#379 Use automatic versioning
  build.bat
  dub.json
  makefile
  release-windows.sh
  release.sh
  src/dfmt/main.d
Labels: auto-merge-squash

#383 deactivate testing with DMD nightly
  .travis.yml
Labels: auto-merge-squash

#387 Synchronize master branch with old 0.x.x
  build.bat
  dub.json
  makefile
  release-windows.sh
  release.sh
  src/dfmt/main.d
Labels: auto-merge

#389 Properly format enum member attributes and parameter attributes (#375)
  src/dfmt/ast_info.d
  src/dfmt/formatter.d
  tests/allman/enum_attribs.d.ref
  tests/allman/func_param_attrib.d.ref
  tests/allman/lambda_param_attrib.d.ref
  tests/enum_attribs.d
  tests/func_param_attrib.d
  tests/lambda_param_attrib.d
  tests/otbs/enum_attribs.d.ref
  tests/otbs/func_param_attrib.d.ref
  tests/otbs/lambda_param_attrib.d.ref
Labels: auto-merge-rebase
